<?php
/**
 * @file
 * Code for the Master thesis config feature.
 */

include_once 'software_advisor_config.features.inc';

use Drupal\software_advisor\SoftwareAdvisor;

/**
 * Implements hook_theme_registry_alter().
 */
function software_advisor_config_theme_registry_alter(&$theme_registry) {
  $theme_registry['rangefield']['function'] = 'software_advisor_config_theme_rangefield';
}

/**
 * Returns HTML for a rangefield form element.
 *
 * Overrides original theme function to remove the form-text class.
 *
 * @see theme_rangefield()
 */
function software_advisor_config_theme_rangefield($variables) {
  $element = $variables['element'];
  $element['#attributes']['type'] = 'range';
  element_set_attributes($element, array('id', 'name', 'value', 'step', 'min', 'max'));
  _form_set_class($element, array('form-range'));

  $output = '<input' . drupal_attributes($element['#attributes']) . ' />';

  return $output;
}

/**
 * Implements hook_node_view_alter().
 */
function software_advisor_config_node_view_alter(&$build) {
  $advisor = SoftwareAdvisor::create($build['#node']);
  $build['software_advisor'] = $advisor->generateSuggestionsRenderArray();
}
