<?php
/**
 * @file
 * Code for the Master thesis config feature.
 */

include_once 'software_advisor_config.features.inc';


/**
 * Implements hook_theme_registry_alter().
 */
function software_advisor_config_theme_registry_alter(&$theme_registry) {
  $theme_registry['rangefield']['function'] = 'software_advisor_config_theme_rangefield';
}

/**
 * Returns HTML for a rangefield form element.
 *
 * Override original theme funciton to remove the form-text class.
 *
 * @param $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #title, #value, #description, #min, #max, #attributes,
 *     #step.
 *
 * @ingroup themeable
 */
function software_advisor_config_theme_rangefield($variables) {
  $element = $variables['element'];
  $element['#attributes']['type'] = 'range';
  element_set_attributes($element, array('id', 'name', 'value', 'step', 'min', 'max'));
  _form_set_class($element, array('form-range'));

  $output = '<input' . drupal_attributes($element['#attributes']) . ' />';

  return $output;
}
