<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_menu().
 */
function software_advisor_import_menu() {
  $items['software-advisor/import'] = array(
    'title' => 'Data importer',
    'page arguments' => array('software_advisor_import_form'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('mt import'),
    'file' => 'software_advisor_import.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
